<a href="https://colab.research.google.com/github/SalehMehrabani/Artifical-Intelligance/blob/main/NN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Give you info about GPU running for your Run time -> Iy selected GPU as Core running
!nvidia-smi

In [1]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
print(torch.__version__)

1.13.1+cu116


# Tensor

In [38]:
torch.range(start=0, 
            end=6, 
            dtype=torch.int16)

<ipython-input-38-a8ad59b59680>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,


tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int16)

In [42]:
z1=torch.arange(start=1,
                end=10,
                step=4)
z1.dtype

torch.int64

In [33]:
torch.zeros_like(input=z1)

tensor([0, 0, 0])

**Note:** Tensor datatype is one of the 3 big errors you will run into PyTorch & Deep Learning:
1. Tensor Not Right DataType
2. Tensor Not Right Shape
3. Tensor Not on Right Device

In [41]:
z2=torch.tensor([3,4,5],
                dtype=torch.int, #Type of data -> default= float32
                device="cuda", # Default= CPU
                requires_grad=False #PyTorch Keeping track of changing in gradient value
                )
z2

tensor([3, 4, 5], dtype=torch.int32)

In [48]:
#change data type of tensor
z2=z2.type(torch.float16)
z2

tensor([[0.0792, 0.9966, 0.4690],
        [0.5542, 0.3018, 0.2211],
        [0.9136, 0.8901, 0.1002]], dtype=torch.float16)