<a href="https://colab.research.google.com/github/SalehMehrabani/Artifical-Intelligance/blob/main/NN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Give you info about GPU running for your Run time -> Iy selected GPU as Core running
!nvidia-smi

In [2]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

1.13.1+cu116


# Tensor

In [ ]:
torch.range(start=0, 
            end=6, 
            dtype=torch.int16)

<ipython-input-38-a8ad59b59680>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,


tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int16)

In [ ]:
z1=torch.arange(start=1,
                end=10,
                step=4)
z1.dtype

torch.int64

In [ ]:
torch.zeros_like(input=z1)

tensor([0, 0, 0])

**Note:** Tensor datatype is one of the 3 big errors you will run into PyTorch & Deep Learning:
1. Tensor Not Right DataType
2. Tensor Not Right Shape
3. Tensor Not on Right Device

In [ ]:
z2=torch.tensor([3,4,5],
                dtype=torch.int, #Type of data -> default= float32
                device="cuda", # Default= CPU
                requires_grad=False #PyTorch Keeping track of changing in gradient value
                )
z2

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
#change data type of tensor
z2=z2.type(torch.float16)
z2

tensor([[0.0792, 0.9966, 0.4690],
        [0.5542, 0.3018, 0.2211],
        [0.9136, 0.8901, 0.1002]], dtype=torch.float16)

###Manipulating Tensors (Tensor operation)

Tensor opertions include:
* Addition
* Subtraction 
* Multiplication(elemnt -wise)
* Division
* Matrix Multiplication (Dot Product) 
      The inner dimension must match 
      The resulting matrix has the shape of the outer dimension



One of the most common erero in Deep Learning is the Shape Error (Specially in Martix Multipliciation)

In [4]:
tensor= torch.rand(1,3)
print(tensor)

tensor([[0.3192, 0.3221, 0.6230]])


In [5]:
tensor +10

tensor([[10.3192, 10.3221, 10.6230]])

In [11]:
# Better to use PyTorch Operation
torch.mul(tensor, 10)
torch.add(tensor, 20)

tensor([[20.3192, 20.3221, 20.6230]])

In [24]:
#Matrix Multiplication
#Retrun The Time Complexity of the running block
%%time
tensor=torch.tensor([1,2,3])
torch.matmul(tensor, tensor)
# tensor @ tensor

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.23 ms


tensor(14)

In [23]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.19 ms, sys: 21 µs, total: 1.21 ms
Wall time: 2.01 ms


tensor(14)

In [ ]:
#short vesion of the matrix maltiplication
tensorA=torch.randint(1,100,(2,3))
tensorB=torch.rand(3,2)
# In matrix multipluication the Data Type of the two matrix must be the identical
torch.mm(tensorA, tensorB)

###Transposing Tensor

In [36]:
Tensor1=torch.rand(2,3)
Tensor1, Tensor1.shape, Tensor1.T, Tensor1.T.shape

(tensor([[0.6817, 0.5632, 0.4956],
         [0.2157, 0.7021, 0.7879]]),
 torch.Size([2, 3]),
 tensor([[0.6817, 0.2157],
         [0.5632, 0.7021],
         [0.4956, 0.7879]]),
 torch.Size([3, 2]))