<a href="https://colab.research.google.com/github/SalehMehrabani/Artifical-Intelligance/blob/main/NN3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Give you info about GPU running for your Run time -> Iy selected GPU as Core running
!nvidia-smi

In [1]:
import torch 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

1.13.1+cu116


# Tensor

In [ ]:
torch.range(start=0, 
            end=6, 
            dtype=torch.int16)

<ipython-input-38-a8ad59b59680>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=0,


tensor([0, 1, 2, 3, 4, 5, 6], dtype=torch.int16)

In [ ]:
z1=torch.arange(start=1,
                end=10,
                step=4)
z1.dtype

torch.int64

In [ ]:
torch.zeros_like(input=z1)

tensor([0, 0, 0])

**Note:** Tensor datatype is one of the 3 big errors you will run into PyTorch & Deep Learning:
1. Tensor Not Right DataType
2. Tensor Not Right Shape
3. Tensor Not on Right Device

In [ ]:
z2=torch.tensor([3,4,5],
                dtype=torch.int, #Type of data -> default= float32
                device="cuda", # Default= CPU
                requires_grad=False #PyTorch Keeping track of changing in gradient value
                )
z2

tensor([3, 4, 5], dtype=torch.int32)

In [ ]:
#change data type of tensor
z2=z2.type(torch.float16)
z2

tensor([[0.0792, 0.9966, 0.4690],
        [0.5542, 0.3018, 0.2211],
        [0.9136, 0.8901, 0.1002]], dtype=torch.float16)

###Manipulating Tensors (Tensor operation)

Tensor opertions include:
* Addition
* Subtraction 
* Multiplication(elemnt -wise)
* Division
* Matrix Multiplication (Dot Product) 
      The inner dimension must match 
      The resulting matrix has the shape of the outer dimension



One of the most common erero in Deep Learning is the Shape Error (Specially in Martix Multipliciation)

In [ ]:
tensor= torch.rand(1,3)
print(tensor)

tensor([[0.3192, 0.3221, 0.6230]])


In [ ]:
tensor +10

tensor([[10.3192, 10.3221, 10.6230]])

In [ ]:
# Better to use PyTorch Operation
torch.mul(tensor, 10)
torch.add(tensor, 20)

tensor([[20.3192, 20.3221, 20.6230]])

In [ ]:
#Matrix Multiplication
#Retrun The Time Complexity of the running block
%%time
tensor=torch.tensor([1,2,3])
torch.matmul(tensor, tensor)
# tensor @ tensor

CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 1.23 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.19 ms, sys: 21 µs, total: 1.21 ms
Wall time: 2.01 ms


tensor(14)

In [ ]:
#short vesion of the matrix maltiplication
tensorA=torch.randint(1,100,(2,3))
tensorB=torch.rand(3,2)
# In matrix multipluication the Data Type of the two matrix must be the identical
torch.mm(tensorA, tensorB)

###Transposing Tensor
[Usefull Website Visulization](http://matrixmultiplication.xyz/)


In [ ]:
Tensor1=torch.rand(2,3)
Tensor1, Tensor1.shape, Tensor1.T, Tensor1.T.shape

(tensor([[0.6817, 0.5632, 0.4956],
         [0.2157, 0.7021, 0.7879]]),
 torch.Size([2, 3]),
 tensor([[0.6817, 0.2157],
         [0.5632, 0.7021],
         [0.4956, 0.7879]]),
 torch.Size([3, 2]))

##Finding the min, max, mean, sum, etc (tensor aggregation)*italicized text*

In [2]:
x= torch.rand(3,3)
x

tensor([[0.8464, 0.5463, 0.7889],
        [0.4869, 0.2642, 0.8985],
        [0.7151, 0.9848, 0.7365]])

In [3]:
torch.min(x)

tensor(0.2642)

In [4]:
torch.max(x)

tensor(0.9848)

In [8]:
# Input dtype should be either floating point or complex number
torch.mean(x.type(torch.float32)) , x.type(torch.float16).mean()

(tensor(0.6964), tensor(0.6963, dtype=torch.float16))

In [6]:
torch.std(x)

tensor(0.2264)

In [9]:
torch.sum(x)

tensor(6.2676)

##Tesno argmax, argmin --> The positional min and max

In [11]:
torch.argmin(x)

tensor(4)

In [13]:
torch.argmax(x)

tensor(7)

## Reshaping, Stacking, Squeezing and unsqueezing tensors
* Squeeze --> Remove 1 Dimension from the tensor
* Unsqueeze --> Add 1 Diemension to the tensor
* Permute --> Return a view of the input with dimension permuted (swapped) in a certain way

In [41]:
x= torch.arange(1., 10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [39]:
#Add an extran dimension --> The size of the elemet must be equal to the pervious one
x_reshaped= x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]), torch.Size([2, 5]))

In [43]:
#change the view 
#changing z, changes x, (because a view of a tensor shares the same memory as the orginal input)
z=x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
#Staks Tensor on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])